package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"ewisuru/scoreboard/graph/model"
	"fmt"
)

// Players is the resolver for the players field.
func (r *queryResolver) Players(ctx context.Context) (*model.Player, error) {
	panic(fmt.Errorf("not implemented: Players - players"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
